# Generated by Django 5.2.5 on 2025-09-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apparel', '0002_alter_apparel_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apparel',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
