# Generated by Django 5.2.5 on 2025-09-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apparel', '0003_alter_apparel_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='apparel',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
