# Generated by Django 5.2.5 on 2025-09-03 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apparel', '0004_apparel_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apparel',
            name='slug',
        ),
    ]
