# Generated by Django 5.2.5 on 2025-09-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apparel', '0006_pack_apparel_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
