# Generated by Django 5.2.5 on 2025-09-10 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apparel', '0007_pack_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apparel',
            name='pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apparels', to='apparel.pack'),
        ),
    ]
